openapi: 3.0.0
info:
  title: Antstack Task
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /v1/invoice:
    post:
      tags:
        - default
      summary: Create Bill
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                - item: Classical Songs Collection
                  itemCategory: Music
                  quantity: 1
                  price: 500
                - item: Pants
                  itemCategory: Clothes
                  quantity: 2
                  price: 1200
      responses:
        '201':
          description: Created
          headers:
            X-Powered-By:
              schema:
                type: string
                example: Express
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '479'
            ETag:
              schema:
                type: string
                example: W/"1df-xZ5GfvtA7IuEyLJ9oMZQUnIs/+Y"
            Date:
              schema:
                type: string
                example: Thu, 26 May 2022 05:42:44 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: '201: Success'
                  value:
                    success: true
                    result:
                      timestamp: '2022-05-26T05:42:44.303Z'
                      items:
                        - item: Black Swan
                          taxRate: 0
                          subTotal: 300
                          taxAmount: 0
                          totalAmount: 300
                        - item: Headache pills
                          taxRate: 5
                          subTotal: 250
                          taxAmount: 12.5
                          totalAmount: 262.5
                        - item: Perfume
                          taxRate: 18
                          subTotal: 4000
                          taxAmount: 720
                          totalAmount: 4720
                        - item: Sandwich
                          taxRate: 5
                          subTotal: 400
                          taxAmount: 20
                          totalAmount: 420
                      subTotal: 5702.5
                      discountRate: 5
                      discount: 285.13
                      total: 5417.37
                example-1:
                  summary: '201: Conditional tax rates'
                  value:
                    success: true
                    result:
                      timestamp: '2022-05-26T05:43:40.125Z'
                      items:
                        - item: Classical Songs Collection
                          taxRate: 3
                          subTotal: 500
                          taxAmount: 15
                          totalAmount: 515
                        - item: Pants
                          taxRate: 12
                          subTotal: 2400
                          taxAmount: 288
                          totalAmount: 2688
                      subTotal: 3203
                      discountRate: 5
                      discount: 160.15
                      total: 3042.85
        '400':
          description: Bad Request
          headers:
            X-Powered-By:
              schema:
                type: string
                example: Express
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
                example: '110'
            ETag:
              schema:
                type: string
                example: W/"6e-hB2BXUwoAFHsUFuYvaa7y2cCXWs"
            Date:
              schema:
                type: string
                example: Thu, 26 May 2022 04:34:05 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            Keep-Alive:
              schema:
                type: string
                example: timeout=5
          content:
            application/json:
              schema:
                type: object
              example:
                success: false
                message: >-
                  "itemCategory" must be one of [Book, Clothes, Food, Medicine,
                  Music, Imported]
